<a href="https://colab.research.google.com/github/Hitesh123mori/Feature_Selection---MachineLearning/blob/main/featureselection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [323]:
import pandas as pd
import numpy as np
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import RFE
from sklearn.feature_selection import chi2
from sklearn import preprocessing
from numpy import set_printoptions
from sklearn.linear_model import LogisticRegression


### **Univariate**

In [260]:
df = pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [261]:
encoder = preprocessing.LabelEncoder()



In [262]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [263]:
encoder.fit(df['Species'])

arr = list(encoder.transform(df['Species']))

df['Species'] = arr

df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [264]:
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [265]:
x.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [266]:
y.head(5)

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int64

In [267]:
test = SelectKBest(score_func=chi2,k=3)
fit = test.fit(x,y)

set_printoptions(precision=1)

print(fit.scores_)

featured_data = fit.transform(x)

print(featured_data[0:5])

# highest score indicates more significant feature and it selected to further

[3311.3   10.8    3.6  116.2   67.2]
[[1.  1.4 0.2]
 [2.  1.4 0.2]
 [3.  1.3 0.2]
 [4.  1.5 0.2]
 [5.  1.4 0.2]]


### Recursive **Feature** Elimination

In [294]:
df2 = pd.read_csv("DatasetCompany.csv")



In [295]:
encoder = preprocessing.LabelEncoder()


arr2 = list(encoder.fit_transform(df2['Gender']))
df2['Gender'] = arr2

arr3 = list(encoder.fit_transform(df2['Education']))
df2['Education'] = arr3

In [296]:
df2.isnull().mean()

Entrollment Number    0.000000
Age                   0.121951
Gender                0.000000
City Index            0.219512
Education             0.000000
Training Hours        0.097561
Experience            0.219512
Selection             0.243902
dtype: float64

In [297]:
df2['Age'].mode()

df2['Age'].fillna("34",inplace=True)

df2['Age'].isnull().mean()


0.0

In [298]:
df2['City Index'].mode()

df2['City Index'].fillna("0.34",inplace=True)

df2['City Index'].isnull().mean()

0.0

In [299]:
df2['Training Hours'].mode()

df2['Training Hours'].fillna("2.0",inplace=True)

df2['Training Hours'].isnull().mean()

0.0

In [300]:
df2['Experience'].mode()

df2['Experience'].fillna("9",inplace=True)

df2['Experience'].isnull().mean()

0.0

In [313]:
df2['Selection'].mode()

df2['Selection'].fillna("1.0",inplace=True)

df2['Selection'].isnull().mean()


0.0

In [316]:
y.unique()

y = y.astype(float).astype(int)


y.unique()

array([1, 0])

In [309]:
x = df2.iloc[:,0:-1]
y  =  df2.iloc[:,-1]


In [317]:
x.head(5)

Entrollment Number   Age  Gender City Index  Education Training Hours  \
0                   1  20.0       1       0.98          1           20.0   
1                   2  18.0       1        0.6          1            2.0   
2                   3  23.0       1        0.7          1           12.0   
3                   4  18.0       0        0.3          0           10.0   
4                   5  12.0       0       0.23          1           12.0   

  Experience  
0        5.0  
1        3.0  
2        3.0  
3        4.0  
4          9

In [318]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Selection, dtype: int64

In [319]:
model = LogisticRegression()
rfe =  RFE(model, n_features_to_select = 3)
fit = rfe.fit(x,y)

In [320]:
selected_features = fit.support_

print(selected_features)



[False False  True False  True  True False]


In [321]:
selected_features_ranking = fit.ranking_

print(selected_features_ranking)

[5 4 1 3 1 1 2]


In [322]:
print(fit.estimator_)

LogisticRegression()
